services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-tracker-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/ai_tracker.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - DEBUG=true
    volumes:
      - backend_data:/app/data
    restart: unless-stopped

  frontend:
    image: nginx:alpine
    container_name: ai-tracker-frontend-simple
    ports:
      - "3000:80"
    volumes:
      - ./frontend-simple:/usr/share/nginx/html:ro
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend_data:
