version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-tracker-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/ai_tracker.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - DEBUG=true
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - ai-tracker-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-tracker-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - ai-tracker-network

volumes:
  backend_data:

networks:
  ai-tracker-network:
    driver: bridge
